### ISSUE TITLE
(Willing to PR) Custom line-length for generated code

### ISSUE THREAD

**Issue by fzyzcjy** [google/json_serializable.dart#1105]
Hi thanks for the wonderful lib! I would appreciate it if the generated `.g.dart` code could be 120-character in width. I can make a PR for this.

How to implement this: https://github.com/dart-lang/build/issues/3250

**Comment by ekuleshov** [comment]
This is somewhat critical because the `dart format` command does not allow to exclude generated files, e.g. when running `dart format -o none --line-length 120 --set-exit-if-changed lib/`

With `--line-length 120` and when enforcing project's code formatting in an automated field we have to manually reformat generated code in order to pass the build.

It would be really helpful to have an option to specify an option to pass line length for the generated code to the pageWidth parameter of the `DartFormatter` used by `json_serializable` generator.

PS: an alternative could be to support an option to exclude some files in the `dart format` command, so it would address the line length issue with other code gens

**Comment by kevmoo** [comment]
formatting is handled by `source_gen`. We could add an option there like we have for other configuration.

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/source_gen/issues/424

**Comment by ekuleshov** [comment]
> See [dart-lang/source_gen#424](https://github.com/dart-lang/source_gen/issues/424)

@kevmoo this is a quote from there :-/

> We don't have plans on making this a build.yaml level configuration or similar because we don't expect users to change the line length. That option in the formatter mainly exists for the purposes of testing the formatter.

I would be okay to have a config option, so the line length would be picked up from there when code gens are using the `source_gen`.

But now it sounds like both options are being rejected by the Dart team?

PS: in my own code gens I've been using `code_builder` instead of `source_gen`. Is that wrong? The former has `source_gen` as a dev dependency.

```
    Library library = ...
    DartEmitter emitter = DartEmitter(useNullSafetySyntax: true);
    StringSink res = library.accept(emitter);
    return DartFormatter().format('$res');
```

**Comment by kevmoo** [comment]
@ekuleshov `code_builder` vs `source_gen` is orthogonal, honestly.
