### ISSUE TITLE
Getting a null error when converting from Firebase a complex object, how to debug?

### ISSUE THREAD

**Issue by giorgio79** [google/json_serializable.dart#1328]
Hello,

I have a complex object and when reading from Firebase, I started getting this error
` type 'Null' is not a subtype of type 'Map<dynamic, dynamic>' in type cast
`

Its quite cryptic, no error line in the object_g.dart file, or the actual propert name. How could I debug this? (without printing each item one by one?)

**Comment by rorystephenson** [comment]
I've got a similar issue. I guess it's not really Firebase specific, it's an issue whenever you have nested json objects and deserialisation fails because a non-nullable field is null. Ideally there would be an indication of what field was missing and where in the json structure the missing field was expected.

I suppose this can be somewhat improved by manually wrapping each nested objects fromJson in a try/catch but you still won't know which field was missing and in my case the model classes are generated automatically so adding the try/catch statements is not possible without a change to the model generator.

**Comment by walid-ashik** [comment]
is there any update on this? still seems like it's huge burden to work with a large object

**Comment by kevmoo** [comment]
You can always use `checked` mode to help here! Just keep in mind it adds quite a bit of runtime overhead.

https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/checked.html

**Comment by kevmoo** [comment]
Also, keep in mind using a debugger can be helpful here, too!
