### ISSUE TITLE
[Bug][Flutter for Web]generated code has error for Flutter for Web

### ISSUE THREAD

**Issue by shinriyo** [google/json_serializable.dart#656]
# my version

```
> flutter --version
Flutter 1.19.0-4.1.pre • channel beta •
https://github.com/flutter/flutter.git
Framework • revision f994b76974 (5 days ago) • 2020-06-09 15:53:13 -0700
Engine • revision 9a28c3bcf4
Tools • Dart 2.9.0 (build 2.9.0-14.1.beta)
```

# What happened

I created `DateTime`
it occurs error 
```
    createdAt: json['createdAt'] == null
        ? null
        : DateTime.parse(json['createdAt'] as String),
```

```
stack_trace_mapper.js:265 Uncaught Bad state: Source maps are not done loading.
```
# How to fix

just replace `as String` to `toString`

`DateTime.parse(json['createdAt']toString()),`

**Comment by nstrelow** [comment]
I seem to be having the same issue.
It is super hard to debug, as it only happens in the release version the javascript is minified (wasn't able to link to sourcemaps, probably my inability).

After finding this and changing the code back and forth, I am confident changing from `as String` to `.toString()` fixed the problem.

Minified error examples:
```
Invalid argument(s): Type minified:fo not supported.

Another exception was thrown: Instance of 'minified:fT<void>'
```

What could be the problem here?
I know as String should be removed at runtime, so somehow the JSON date is not compatible String?

**Comment by nstrelow** [comment]
Any ideas why this is happening?

**Comment by kevmoo** [comment]
What is the exact data coming across? Sounds like it's not a normal string. Will need more info.

**Comment by nstrelow** [comment]
It was a DateTime object, IIRC.
Sadly I have since switched backend frameworks and added null-safety. Working now for me.

So either the DateTime is in a correct format now, or some Flutter changes have since fixed it.



The problem was occuring when using what was generated by json_serializable and **only in release mode:**
```
DateTime.parse(json['timestamp'] as String),
```

And I was able to fix it, by keeping the generated file x.g.dart with a `toString()` instead of `as String`:
```
DateTime.parse(json['timestamp'].toString())
```

from my side, this issue can be closed, if @shinriyo doesn't still have the problem.
