### ISSUE TITLE
build_runner build failed

### ISSUE THREAD

**Issue by spermicide** [google/json_serializable.dart#692]
use your official example on this page:
https://pub.dev/packages/json_serializable

when I run
flutter packages pub run build_runner build

it says:

```
Precompiling executable...
Precompiled build_runner:build_runner.
[INFO] Generating build script...
[INFO] Generating build script completed, took 252ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 8.0s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 402ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] Generating SDK summary...
[SEVERE] json_serializable:json_serializable on lib/example.dart:

Bad state: Unexpected diagnostics:
F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
[SEVERE] json_serializable:json_serializable on lib/example.dart:

Bad state: Unexpected diagnostics:
F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
[SEVERE] json_serializable:json_serializable on lib/example.dart:

Bad state: Unexpected diagnostics:
F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
[SEVERE] json_serializable:json_serializable on lib/example.dart:

Bad state: Unexpected diagnostics:
F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
[SEVERE] json_serializable:json_serializable on lib/example.dart:

Bad state: Unexpected diagnostics:
F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
[INFO] 1.4s elapsed, 1/5 actions completed.
[INFO] 2.5s elapsed, 1/5 actions completed.
[INFO] 3.6s elapsed, 1/5 actions completed.
[INFO] 4.7s elapsed, 1/5 actions completed.
[INFO] 5.8s elapsed, 1/5 actions completed.
[INFO] 6.9s elapsed, 1/5 actions completed.
[INFO] 8.0s elapsed, 1/5 actions completed.
[INFO] 9.1s elapsed, 1/5 actions completed.
[INFO] 10.2s elapsed, 1/5 actions completed.
[INFO] 11.3s elapsed, 1/5 actions completed.
[INFO] 12.4s elapsed, 1/5 actions completed.
[INFO] 13.5s elapsed, 1/5 actions completed.

```

and nothing generated

this is my version

```

dev_dependencies:

  build_runner: ^1.0.0
  json_serializable: ^3.4.0

dependencies:

  json_annotation: ^3.0.0

Flutter 1.20.2 

Tools • Dart 2.9.1
```

Hope you to tell me how can I do
thanks!

**Comment by DurianWyn** [comment]
> use your official example on this page:
> https://pub.dev/packages/json_serializable
> 
> when I run
> flutter packages pub run build_runner build
> 
> it says:
> 
> ```
> Precompiling executable...
> Precompiled build_runner:build_runner.
> [INFO] Generating build script...
> [INFO] Generating build script completed, took 252ms
> 
> [WARNING] Deleted previous snapshot due to missing asset graph.
> [INFO] Creating build script snapshot......
> [INFO] Creating build script snapshot... completed, took 8.0s
> 
> [INFO] Initializing inputs
> [INFO] Building new asset graph...
> [INFO] Building new asset graph completed, took 402ms
> 
> [INFO] Checking for unexpected pre-existing outputs....
> [INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
> 
> [INFO] Running build...
> [INFO] Generating SDK summary...
> [SEVERE] json_serializable:json_serializable on lib/example.dart:
> 
> Bad state: Unexpected diagnostics:
> F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
> [SEVERE] json_serializable:json_serializable on lib/example.dart:
> 
> Bad state: Unexpected diagnostics:
> F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
> [SEVERE] json_serializable:json_serializable on lib/example.dart:
> 
> Bad state: Unexpected diagnostics:
> F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
> [SEVERE] json_serializable:json_serializable on lib/example.dart:
> 
> Bad state: Unexpected diagnostics:
> F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
> [SEVERE] json_serializable:json_serializable on lib/example.dart:
> 
> Bad state: Unexpected diagnostics:
> F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
> [INFO] 1.4s elapsed, 1/5 actions completed.
> [INFO] 2.5s elapsed, 1/5 actions completed.
> [INFO] 3.6s elapsed, 1/5 actions completed.
> [INFO] 4.7s elapsed, 1/5 actions completed.
> [INFO] 5.8s elapsed, 1/5 actions completed.
> [INFO] 6.9s elapsed, 1/5 actions completed.
> [INFO] 8.0s elapsed, 1/5 actions completed.
> [INFO] 9.1s elapsed, 1/5 actions completed.
> [INFO] 10.2s elapsed, 1/5 actions completed.
> [INFO] 11.3s elapsed, 1/5 actions completed.
> [INFO] 12.4s elapsed, 1/5 actions completed.
> [INFO] 13.5s elapsed, 1/5 actions completed.
> ```
> 
> and nothing generated
> 
> this is my version
> 
> ```
> 
> dev_dependencies:
> 
>   build_runner: ^1.0.0
>   json_serializable: ^3.4.0
> 
> dependencies:
> 
>   json_annotation: ^3.0.0
> 
> Flutter 1.20.2 
> 
> Tools • Dart 2.9.1
> ```
> 
> Hope you to tell me how can I do
> thanks!


I also encountered the same problem, so I switched from flutter 1.20.2 to 1.17.5, and it worked normally on 1.17.5

**Comment by pomegra** [comment]
use your official example on this page:
https://pub.dev/packages/json_serializable

when I run
flutter packages pub run build_runner build

it says:

Precompiling executable...
Precompiled build_runner:build_runner.
[INFO] Generating build script...
[INFO] Generating build script completed, took 252ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 8.0s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 402ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] Generating SDK summary...
[SEVERE] json_serializable:json_serializable on lib/example.dart:

Bad state: Unexpected diagnostics:
F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
[SEVERE] json_serializable:json_serializable on lib/example.dart:

Bad state: Unexpected diagnostics:
F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
[SEVERE] json_serializable:json_serializable on lib/example.dart:

Bad state: Unexpected diagnostics:
F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
[SEVERE] json_serializable:json_serializable on lib/example.dart:

Bad state: Unexpected diagnostics:
F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
[SEVERE] json_serializable:json_serializable on lib/example.dart:

Bad state: Unexpected diagnostics:
F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
[INFO] 1.4s elapsed, 1/5 actions completed.
[INFO] 2.5s elapsed, 1/5 actions completed.
[INFO] 3.6s elapsed, 1/5 actions completed.
[INFO] 4.7s elapsed, 1/5 actions completed.
[INFO] 5.8s elapsed, 1/5 actions completed.
[INFO] 6.9s elapsed, 1/5 actions completed.
[INFO] 8.0s elapsed, 1/5 actions completed.
[INFO] 9.1s elapsed, 1/5 actions completed.
[INFO] 10.2s elapsed, 1/5 actions completed.
[INFO] 11.3s elapsed, 1/5 actions completed.
[INFO] 12.4s elapsed, 1/5 actions completed.
[INFO] 13.5s elapsed, 1/5 actions completed.
and nothing generated

this is my version


dev_dependencies:

  build_runner: ^1.0.0
  json_serializable: ^3.4.0

dependencies:

  json_annotation: ^3.0.0

Flutter 1.20.2 

Tools • Dart 2.9.1
Hope you to tell me how can I do
thanks!

**Comment by DurianWyn** [comment]
> use your official example on this page:
> https://pub.dev/packages/json_serializable
> 
> when I run
> flutter packages pub run build_runner build
> 
> it says:
> 
> Precompiling executable...
> Precompiled build_runner:build_runner.
> [INFO] Generating build script...
> [INFO] Generating build script completed, took 252ms
> 
> [WARNING] Deleted previous snapshot due to missing asset graph.
> [INFO] Creating build script snapshot......
> [INFO] Creating build script snapshot... completed, took 8.0s
> 
> [INFO] Initializing inputs
> [INFO] Building new asset graph...
> [INFO] Building new asset graph completed, took 402ms
> 
> [INFO] Checking for unexpected pre-existing outputs....
> [INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
> 
> [INFO] Running build...
> [INFO] Generating SDK summary...
> [SEVERE] json_serializable:json_serializable on lib/example.dart:
> 
> Bad state: Unexpected diagnostics:
> F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
> [SEVERE] json_serializable:json_serializable on lib/example.dart:
> 
> Bad state: Unexpected diagnostics:
> F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
> [SEVERE] json_serializable:json_serializable on lib/example.dart:
> 
> Bad state: Unexpected diagnostics:
> F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
> [SEVERE] json_serializable:json_serializable on lib/example.dart:
> 
> Bad state: Unexpected diagnostics:
> F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
> [SEVERE] json_serializable:json_serializable on lib/example.dart:
> 
> Bad state: Unexpected diagnostics:
> F:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
> [INFO] 1.4s elapsed, 1/5 actions completed.
> [INFO] 2.5s elapsed, 1/5 actions completed.
> [INFO] 3.6s elapsed, 1/5 actions completed.
> [INFO] 4.7s elapsed, 1/5 actions completed.
> [INFO] 5.8s elapsed, 1/5 actions completed.
> [INFO] 6.9s elapsed, 1/5 actions completed.
> [INFO] 8.0s elapsed, 1/5 actions completed.
> [INFO] 9.1s elapsed, 1/5 actions completed.
> [INFO] 10.2s elapsed, 1/5 actions completed.
> [INFO] 11.3s elapsed, 1/5 actions completed.
> [INFO] 12.4s elapsed, 1/5 actions completed.
> [INFO] 13.5s elapsed, 1/5 actions completed.
> and nothing generated
> 
> this is my version
> 
> dev_dependencies:
> 
> build_runner: ^1.0.0
> json_serializable: ^3.4.0
> 
> dependencies:
> 
> json_annotation: ^3.0.0
> 
> Flutter 1.20.2
> 
> Tools • Dart 2.9.1
> Hope you to tell me how can I do
> thanks!


I manually downgraded the flutter version, you can execute "flutter version + version number" to downgrade to the version you want to use

**Comment by poshpawstudio** [comment]
This issue is blocking me to upgrade Flutter to 1.20.

**Comment by jakemac53** [comment]
What version of `analyzer` do you have? You can run `pub deps` to see this or check your `pubspec.lock` file.

**Comment by jakemac53** [comment]
Looking into this one possible solution is set your `build_runner` version to `^1.10.1`. That should work but is a roundabout fix.

I am trying to figure out the real issue here, the sdk seems to be using invalid syntax `?.[` which maybe was allowed for a period of time or something I am not sure (now you just do `?[`).

**Comment by jakemac53** [comment]
Just to follow up here this was definitely the problem, see the related sdk issue about the syntax change https://github.com/dart-lang/language/issues/376.

Since then the support for `?.[` has been removed but the min sdk for that analyzer version was not set to not include sdks that use that syntax, hence the error.

You need to ensure you get an older analyzer version in order to successfully analyze this sdk, although I am not totally sure exactly what version you need I know that `0.39.14` works.

**Comment by kevmoo** [comment]
Closing this out as it's not specific to `json_serializable` – although it IS annoying!
